server:
  port: ${PORT:8080}
  servlet:
    context-path: /appsantander

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://${JDBC_DATABASE_USERNAME}:${JDBC_DATABASE_PASSWORD}@${JDBC_DATABASE_HOST}:5432/${JDBC_DATABASE_NAME}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Project created for DIO bootcamp - Santander dev Week
  version: 1.0
